In [2]:
import numpy as np
import math
import scipy.stats

*Задание 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.*

In [15]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [16]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [18]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [22]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [17]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [23]:
np.std(ks)

174.55340157098058

In [24]:
np.std(zp)

59.115480206118605

In [25]:
Kp = np.cov(zp, ks, ddof=0) / (np.std(ks) * np.std(zp))
Kp

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

*Задание 2.
 Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.*

In [3]:
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
x

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [4]:
m = x.mean()
m

118.1

In [5]:
std = (x.var(ddof=1))**0.5
std

10.54566788359614

In [9]:
t_t = scipy.stats.t.ppf(0.975, 9)
t_t

2.2621571627409915

In [10]:
d1 = m - t_t* std/math.sqrt(10)
d1

110.55608365158724

In [11]:
d2 = m + t_t* std/math.sqrt(10)
d2

125.64391634841274

*Задание 3.Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.*

In [12]:
m0 = 174.2
d = 25
n = 27
a = 0.05

In [13]:
d1 = m0 - (1.96*5/math.sqrt(27))
d1

172.31398912064722

In [14]:
d2 = m0 + (1.96*5/math.sqrt(27))
d2

176.08601087935276